module.exports = {
  apps: [
    {
      name: 'remitero',
      cwd: 'C:/Users/ema/Documents/projects/remitero',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 8000',
      env: { NODE_ENV: 'production' },
      env_file: '.env',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'launcher',
      cwd: 'C:/Users/ema/Documents/projects/launcher',
      script: 'server.js',
      env: { PORT: 80 },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'ia',
      cwd: 'C:/Users/ema/Documents/projects/ia',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3001',
      env: { NODE_ENV: 'production' },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'devbot',
      cwd: 'C:/Users/ema/Documents/projects/devbot-orchestrator',
      script: 'server.js',
      env_file: '.env',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'vorum-wa',
      cwd: 'C:/Users/ema/Documents/projects/vorum-wa',
      script: 'index.js',
      env_file: '.env',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
}
